//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace verificarrepetidas
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT_DICCIONARIO_MD5
    {
        public int indici { get; set; }
        public string MD5 { get; set; }
        public string FOTO { get; set; }
    }
}
